options:
  formatter: stylish
  merge-default-rules: false
rules:
  attribute-quotes: 0
  bem-depth: 0
  border-zero: 2
  brace-style:
    - 2
    - style: 'stroustrup'
    - allow-single-line: false
  class-name-format:
    - 2
    - allow-leading-underscore: false
    - convention: hyphenatedlowercase
  clean-import-paths:
    - 0
    - filename-extension: false
    - leading-underscore: false
  declarations-before-nesting: 2
  empty-args: 0
  empty-line-between-blocks:
    - 0
    - allow-single-line-rulesets: false
  extends-before-declarations: 2
  extends-before-mixins: 0
  final-newline: 0
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 2
    - allow-leading-underscore: false
    - convention: camelcase
  hex-length: 0
  hex-notation:
    - 2
    - style: lowercase
  id-name-format:
    - 2
    - allow-leading-underscore: false
    - convention: hyphenatedlowercase
  indentation:
    - 2
    - size: 2
  leading-zero:
    - 2
    - include: true
  max-file-line-count: 0
  max-line-length: 0
  mixin-name-format:
    - 2
    - allow-leading-underscore: false
    - convention: camelcase
  mixins-before-declarations: 2
  nesting-depth:
    - 2
    - max-depth: 6
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 2
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 0
  no-debug: 1
  no-disallowed-properties: 0
  no-duplicate-properties:
    - 0
    - exclude:
      - background
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 0
  no-important: 1
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties:
    - 2
    - extra-properties:
      - animate
      - overflow-scrolling
  no-qualifying-elements:
    - 0
    - allow-element-with-attribute: false
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 0
  no-universal-selectors: 1
  no-url-domains: 0
  no-url-protocols: 0
  no-vendor-prefixes: 0
  no-warn: 1
  one-declaration-per-line: 2
  placeholder-in-extend: 0
  placeholder-name-format:
    - 2
    - allow-leading-underscore: false
    - convention: camelcase
  property-sort-order: 0
  property-units: 0
  pseudo-element: 2
  quotes:
    - 2
    - style: double
  shorthand-values: 2
  single-line-per-selector: 2
  space-after-bang:
    - 2
    - include: false
  space-after-colon:
    - 2
    - include: true
  space-after-comma:
    - 2
    - include: true
  space-around-operator:
    - 2
    - include: true
  space-before-bang:
    - 0
    - include: true
  space-before-brace:
    - 2
    - include: true
  space-before-colon:
    - 2
    - include: false
  space-between-parens:
    - 2
    - include: false
  trailing-semicolon:
    - 2
    - include: true
  url-quotes: 2
  variable-for-property:
    - 2
    - properties:
      - color
      - font-weight
  variable-name-format:
    - 2
    - allow-leading-underscore: true
      convention: snakecase
  zero-unit: 0
